Repository AY2324S1-CS2103T-T13-4/tp, pull requests merged in 2023-10, with the labels that each got.

#61 Find & list merge
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#62 Change clear to reset
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: enhancement

#63 Add new fields for add command with UI changes
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AnimalType.java
  src/main/java/seedu/address/model/person/Availability.java
  src/main/java/seedu/address/model/person/Housing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AnimalTypeTest.java
  src/test/java/seedu/address/model/person/AvailabilityTest.java
  src/test/java/seedu/address/model/person/HousingTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#59 Allow for multiple deletion
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/commons/core/index/Indices.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/commons/core/index/IndicesTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndices.java
Labels: enhancement

#65 Update add feature in UG and fix bug
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug, documentation

#67 Update View, Edit, and Exit commands in UserGuide
  docs/UserGuide.md
Labels: documentation

#73 Update add command and implement sort command with documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/AnimalType.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AnimalTypeTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation, enhancement

#82 Add conditions for NotAvailable, do checks in Person class instead and update user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/AnimalType.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/search/FindCommandArgumentParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: documentation, enhancement

#80 Display number of fosterers deleted
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/commons/core/index/Indices.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/commons/core/index/IndicesTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: documentation, enhancement

#83 Find list userguide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/search/FindCommandArgumentParser.java
  src/main/java/seedu/address/logic/search/SingleTextSearchMatcher.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/search/BinarySearchMatcherTest.java
  src/test/java/seedu/address/logic/search/FieldRangesTest.java
  src/test/java/seedu/address/logic/search/FindCommandArgumentParserTest.java
  src/test/java/seedu/address/logic/search/SingleTextSearchMatcherTest.java
Labels: documentation, enhancement

#84 Update View, Edit, and add Save commands in UserGuide.md
  docs/UserGuide.md
Labels: documentation

#86 Create stats functionality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/screenshots/Delete.png
  docs/images/screenshots/StatsAvail.png
  docs/images/screenshots/StatsCurr.png
  docs/images/screenshots/StatsHousing.png
  src/main/java/seedu/address/logic/commands/StatsAvailCommand.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/commands/StatsCurrentCommand.java
  src/main/java/seedu/address/logic/commands/StatsHousingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/model/person/AnimalType.java
  src/main/java/seedu/address/model/person/Availability.java
  src/main/java/seedu/address/model/person/Housing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsAvailCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCurrentCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsHousingCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StatsCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation, enhancement
