Repository AY2324S1-CS2103T-T13-4/tp, pull requests merged in 2023-11, with the labels that each got.

#91 Format and tidy up user guide
  docs/UserGuide.md
  docs/images/screenshots/AddErrorMessage.png
  docs/images/screenshots/AddSuccess.png
  docs/images/screenshots/HelpWindow.png
  docs/images/screenshots/Sort.png
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: bug, documentation

#88 Fix EditCommand Issue, add SaveCommand, and add field focus functionality
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditFieldCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewExitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ViewModeParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonProfile.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewExitCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewModeParserTest.java
Labels: enhancement

#94 Undo command
  src/main/java/seedu/address/commons/exceptions/DataLoadingException.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
Labels: enhancement

#85 Add Confirmation prompt when attempting to reset address book.
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#96 Change stats to 2dp
  docs/UserGuide.md
  docs/images/screenshots/StatsAvail.png
  docs/images/screenshots/StatsCurr.png
  docs/images/screenshots/StatsCurrent.png
  docs/images/screenshots/StatsHousing.png
  src/main/java/seedu/address/logic/commands/StatsAvailCommand.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/commands/StatsCurrentCommand.java
  src/main/java/seedu/address/logic/commands/StatsHousingCommand.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
Labels: documentation

#92 Add a User Interface Explanation Section in UserGuide
  docs/UserGuide.md
  docs/images/screenshots/BeforeEnteringName.png
  docs/images/screenshots/BensonMeieView.png
  docs/images/screenshots/CursorBackToCommandbox.png
  docs/images/screenshots/EditExample.png
  docs/images/screenshots/ExitCommandNotSavedCancel.png
  docs/images/screenshots/ExitCommandNotSavedWarning.png
  docs/images/screenshots/ExitCommandSavedAfter.png
  docs/images/screenshots/ExitCommandSavedBefore.png
  docs/images/screenshots/ExitProfilePageWithoutDetails.png
  docs/images/screenshots/ExitWithoutSave.png
  docs/images/screenshots/NavigatingFields.png
  docs/images/screenshots/ProfilePage.png
  docs/images/screenshots/SaveCommandAfter.png
  docs/images/screenshots/SaveCommandBefore.png
Labels: documentation

#98 Finalise UG for v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/screenshots/Reset.png
  docs/images/screenshots/ResetConfirm.png
  docs/images/screenshots/Undo.png
  docs/images/screenshots/UndoError.png
Labels: documentation

#97 Undo command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
Labels: bug

#139 Update UG and DG with Delete and Stats features, Fix some PED Documentation Bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteMultipleSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StatsAvailSelfInvDiagram.puml
  docs/diagrams/StatsAvailSequenceDiagram.puml
  docs/diagrams/StatsClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteMultipleSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StatsAvailSelfInvDiagram.png
  docs/images/StatsAvailSequenceDiagram.png
  docs/images/StatsClassDiagram.png
  docs/images/screenshots/HelpWindow.png
  docs/images/screenshots/StatsAllAvail.png
  docs/images/screenshots/StatsTotalPercent.png
  src/main/java/seedu/address/commons/core/index/Indices.java
Labels: documentation

#141 Update PPP + UG updates (Formatting errors + Explain screenshot examples)
  docs/UserGuide.md
  docs/team/butteredyakiimo.md
Labels: documentation

#142 Fix Bugs And Add Testcases
  build.gradle
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/commands/ViewExitCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonProfile.java
  src/main/java/seedu/address/ui/PersonProfileField.java
  src/main/java/seedu/address/ui/PersonProfileNote.java
  src/main/java/seedu/address/ui/PersonProfileTags.java
  src/main/java/seedu/address/ui/UiPart.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CommandTypeTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditFieldCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/SaveCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewExitCommandTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#144 Resolve PED issues and update add and sort command in both UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/screenshots/AddDuplicate.png
  docs/images/screenshots/AddJerry.png
  docs/images/screenshots/AddPete.png
  docs/images/screenshots/AddSuccess.png
  docs/images/screenshots/Sort.png
Labels: bug, documentation

#143 Reset double confirm
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
Labels: bug

#140 Edit DG with Profile class and sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ProfileEditSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiProfileDiagram.puml
  docs/images/ProfileEditSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiProfileDiagram.png
Labels: documentation

#147 Minor tweaks to UG and added PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/screenshots/Reset.png
  docs/images/screenshots/ResetConfirm.png
  docs/team/nananakx-x.md
Labels: documentation

#146 Update DG, PPP, and improve code quality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditFieldSequenceDiagram.puml
  docs/diagrams/EditFieldSequenceDiagramStep1.puml
  docs/diagrams/EditFieldSequenceDiagramStep2.puml
  docs/diagrams/HandleSaveSequenceDiagram.png
  docs/diagrams/HandleSaveSequenceDiagram.puml
  docs/diagrams/IsInViewModeSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MainWindowCommandTypeSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/SaveSequenceDiagram.puml
  docs/diagrams/SaveSequenceDiagramStep1.puml
  docs/diagrams/SaveSequenceDiagramStep2.puml
  docs/images/EditFieldSequenceDiagram.png
  docs/images/EditFieldSequenceDiagramStep1.png
  docs/images/EditFieldSequenceDiagramStep2.png
  docs/images/HandleSaveSequenceDiagram.png
  docs/images/IsInViewModeSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MainWindowCommandTypeSequenceDiagram.png
  docs/images/ParserClasses.png
  docs/images/SaveSequenceDiagram.png
  docs/images/SaveSequenceDiagramStep1.png
  docs/images/SaveSequenceDiagramStep2.png
  docs/images/screenshots/BobYeoh.png
  docs/images/screenshots/ChangeNameToBobYeoh.png
  docs/images/screenshots/EditExample2.png
  docs/images/screenshots/EnterName.png
  docs/images/screenshots/SaveBobYeoh.png
  docs/images/screenshots/SaveExistingFosterer.png
  docs/images/screenshots/SaveNewFosterer.png
  docs/images/screenshots/View1.png
  docs/team/brandon-nam.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: documentation

#148 Read through UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/screenshots/BeforeEnteringName.png
  docs/images/screenshots/BensonMeieView.png
  docs/images/screenshots/CursorBackToCommandbox.png
  docs/images/screenshots/EditExample.png
  docs/images/screenshots/ExitCommandNotSavedCancel.png
  docs/images/screenshots/ExitCommandNotSavedWarning.png
  docs/images/screenshots/ExitCommandSavedAfter.png
  docs/images/screenshots/ExitCommandSavedBefore.png
  docs/images/screenshots/NavigatingFields.png
  docs/images/screenshots/Notes.png
  docs/images/screenshots/SaveCommandAfter.png
  docs/images/screenshots/SaveCommandBefore.png
  docs/images/screenshots/StatsTotalPercent.png
  docs/images/screenshots/ViewCommandExample.png
  docs/team/butteredyakiimo.md
Labels: documentation

#149 Improve code quality, review tests, final check and organisation of documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/nananakx-x.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/AnimalType.java
  src/main/java/seedu/address/model/person/Availability.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Housing.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AnimalTypeTest.java
  src/test/java/seedu/address/model/person/AvailabilityTest.java
  src/test/java/seedu/address/model/person/HousingTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug, documentation

#152 Line breaks and Image size in UG
  docs/UserGuide.md
  docs/images/screenshots/ExitCommandSavedBefore.png
  docs/images/screenshots/NavigatingFields.png
  docs/images/screenshots/SaveCommandAfter.png
  docs/images/screenshots/SaveCommandBefore.png
  docs/images/screenshots/ViewCommandExample.png
Labels: documentation

#160 Add ViewExitCommand explanation in DG and design considerations, improve code quality, add test cases for LogicManager
  docs/DeveloperGuide.md
  docs/diagrams/HandleViewExitSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/SaveSequenceDiagram.puml
  docs/diagrams/ViewExitSequenceDiagram.puml
  docs/diagrams/ViewExitSequenceDiagram1.puml
  docs/diagrams/ViewExitSequenceDiagram2.puml
  docs/diagrams/ViewExitSequenceDiagram3.puml
  docs/images/HandleViewExitSequenceDiagram.png
  docs/images/ParserClasses.png
  docs/images/SaveSequenceDiagram.png
  docs/images/ViewExitSequenceDiagram.png
  docs/images/ViewExitSequenceDiagram1.png
  docs/images/ViewExitSequenceDiagram2.png
  docs/images/ViewExitSequenceDiagram3.png
  docs/team/brandon-nam.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: documentation

#150 Reset and Undo documantation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/HandleSaveSequenceDiagram.png
  docs/diagrams/ResetActivityDiagram.puml
  docs/diagrams/ResetConfirmSequenceDiagram.puml
  docs/diagrams/ResetSequenceDiagram.puml
  docs/diagrams/UndoActivityDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ResetActivityDiagram.png
  docs/images/ResetConfirmSequenceDiagram.png
  docs/images/ResetSequenceDiagram.png
  docs/images/UndoActivityDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/screenshots/ResetPrompt.png
  docs/team/tyruslye.md
Labels: documentation

#170 Adding documentation
  docs/DeveloperGuide.md
  docs/diagrams/ResetConfirmSequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ResetConfirmSequenceDiagram.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation
